language: node_js
node_js:
  - "node"
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - npm install -g typescript
  - cd functions
  - npm install
  - tsc
script:
  - npm run lint